{% set name = "exmol" %}
{% set version = "2.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/exmol-{{ version }}.tar.gz
  sha256: 02fe55edddc9911fec4bdffa6b7d3c420aa29535b099b9d2aa88eaa05d5b0261

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - selfies >=2.0.0
    - matplotlib-base
    - numpy
    - requests
    - tqdm
    - ratelimit
    - rdkit
    - scikit-learn
    - skunk >=0.4.0

test:
  imports:
    - exmol
    - exmol.stoned
  # can't run `pip` check since `rdkit-pypi`
  # is called `rdkit` on conda
#   requires:
#     - pip
#   commands:
#     - pip check

about:
  home: https://ur-whitelab.github.io/exmol/
  summary: Counterfactual generation with STONED SELFIES
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hadim
