{% set name = "exmol" %}
{% set version = "0.5.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/exmol-{{ version }}.tar.gz
  sha256: 9f349f04e8b609962c520900706011f41e441f79c0adc031ce36b8c582efbf3f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - matplotlib-base
    - numpy
    - python >=3.6
    - ratelimit
    - rdkit
    - requests
    - scikit-learn
    - selfies <2
    - tqdm
    - skunk >=0.4.0

test:
  imports:
    - exmol
    - exmol.stoned
  requires:
    - pip

about:
  home: https://ur-whitelab.github.io/exmol/
  summary: Counterfactual generation with STONED SELFIES
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hadim
