{% set name = "exmol" %}
{% set version = "2.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/exmol-{{ version }}.tar.gz
  sha256: 52982a72ae865f5111a1efe73aac0584339490a77fc9dc51bde3f7fd36051c28

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - selfies >=2.0.0
    - matplotlib-base
    - numpy
    - requests
    - tqdm
    - ratelimit
    - rdkit
    - scikit-learn
    - skunk >=0.4.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - exmol
    - exmol.stoned
  # can't run `pip` check since `rdkit-pypi`
  # is called `rdkit` on conda
#   requires:
#     - pip
#   commands:
#     - pip check

about:
  home: https://ur-whitelab.github.io/exmol/
  summary: Counterfactual generation with STONED SELFIES
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hadim
