context:
  name: exmol
  version: "3.2.2"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/exmol-${{ version }}.tar.gz
  sha256: 80d78c520a70a9071d5f54869bc9fbfcb490a7de1a836454670fff00ed0a1623

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
  run:
    - python >=${{ python_min }}
    - selfies >=2.0.0
    - numpy
    - requests
    - tqdm
    - ratelimit
    - rdkit
    - scikit-learn
    - skunk >=0.4.0
    - synspace
    - openai
    - matplotlib-base
    - scipy

tests:
  - python:
      imports:
        - exmol
        - exmol.stoned
      python_version: ${{ python_min }}.*

about:
  summary: Counterfactual generation with STONED SELFIES
  license: MIT
  license_file: LICENSE
  homepage: https://ur-whitelab.github.io/exmol/

extra:
  recipe-maintainers:
    - hadim
